name: ðŸš€ Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸš€ SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "WHOAMI:"
            whoami

            echo "PWD:"
            pwd

            echo "LIST HOME:"
            ls -la /home/globgcbn

            echo "ENTER PROJECT DIR"
            cd /home/globgcbn/quazi.global || exit 1

            echo "LIST PROJECT DIR:"
            ls -la

            echo "GIT STATUS:"
            git status || echo "NOT A GIT REPO"

            echo "GIT BRANCH:"
            git branch || true

            echo "TRY PULL:"
            git pull origin main || git pull origin master